[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=ExtractOnly
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=You are about to execute a file that will destroy your search history and probably put you on so many watchlists. So have fun.
DisplayLicense=C:\Users\Dell\Desktop\Boring Legal Stuff.txt
FinishMessage=Welp, good luck living with the CIA and FBI breating down your neck while you try to forget about all the stuff you saw.
TargetName=C:\Users\Dell\Desktop\Basic Virus.EXE
FriendlyName=Basic Virus
AppLaunched=
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="BadStuff.py"
FILE1="StartingFile.py"
[SourceFiles]
SourceFiles0=C:\Users\Dell\Desktop\Virus Stuff\
[SourceFiles0]
%FILE0%=
%FILE1%=
